name = "zipnotic"
version = "1.1.0"

description = "A grab bag of zip functions."
licences = ["Apache-2.0"]
repository = { type = "github", user = "JosephTLyons", repo = "zipnotic" }

[dependencies]
gleam_stdlib = ">= 0.51.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
